### ISSUE TITLE
Set room's name

### ISSUE THREAD

**Issue by erdnaxeli** [Cadair/matrix-appservice-hangouts#7]
We have the room name (it is shown with `list conversations`), it would be nice to set it as the Matrix room's name too.

**Comment by Cadair** [comment]
It *should* do that already, there seems to be a bug with the whole joining rooms thing at the moment, that my initial debugging last night did not resolve. I will try and get back to it over the weekend.

**Comment by Cadair** [comment]
Is fixed in v0.2.0
